version: '3.8'
services:
  mysql:
    image: 'mysql:8'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-shoutzor}
      - MYSQL_USER=${DB_USERNAME:-shoutzor}
      - MYSQL_PASSWORD=${DB_PASSWORD:-Shoutz0r!}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - shoutzor-backend

  redis:
    image: 'bitnami/redis:7.0'
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-R3disPassw0rd!}
      - REDIS_TLS_ENABLED=${REDIS_TLS_ENABLED:-false}
    networks:
      - shoutzor-backend

  mailhog:
    image: 'mailhog/mailhog'

  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    image: xorinzor/shoutz0r-backend
    ports:
      - "8000:8000"
    environment:
      - OCTANE_HOST=127.0.0.1
      - OCTANE_PORT=8000
      - LOG_LEVEL
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_SCHEME
      - APP_DOMAIN
      - FRONTEND_URL=${FRONTEND_URL:-http://shoutzor.local}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD=${DB_PASSWORD:-Shoutz0r!}
      - LIGHTHOUSE_SUBSCRIPTION_STORAGE=${LIGHTHOUSE_SUBSCRIPTION_STORAGE:-redis}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET:-AppSecr3t!}
      - PUSHER_HOST=${PUSHER_HOST:-echo}
      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-R3disPassw0rd!}
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ENCRYPTION
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
    volumes:
      - tmp:/code
    networks:
      - shoutzor-backend
    depends_on:
      - redis
      - mysql

  worker:
    build:
      context: .
      dockerfile: ./worker.Dockerfile
    image: xorinzor/shoutz0r-worker
    environment:
      - LOG_LEVEL
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_SCHEME
      - APP_DOMAIN
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD=${DB_PASSWORD:-Shoutz0r!}
      - LIGHTHOUSE_SUBSCRIPTION_STORAGE=${LIGHTHOUSE_SUBSCRIPTION_STORAGE:-redis}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET:-AppSecr3t!}
      - PUSHER_HOST=${PUSHER_HOST:-echo}
      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-R3disPassw0rd!}
    volumes:
      - tmp:/code
    depends_on:
      - mysql
      - redis
    networks:
      - shoutzor-backend
    
volumes:
  tmp:

networks:
  shoutzor-backend:
    enable_ipv6: false
