name: Build
on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]
jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install composer packages
        run: composer install --no-dev --prefer-dist
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Backend
        uses: docker/build-push-action@v3
        with:
          file: './backend.Dockerfile'
          push: true
          tags: xorinzor/shoutz0r-backend:latest
      -
        name: Build and push Worker
        uses: docker/build-push-action@v3
        with:
          file: './worker.Dockerfile'
          push: true
          tags: xorinzor/shoutz0r-worker:latest